# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 03:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170322_0153'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
