# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:10
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170322_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
